before_install:
  - yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - yes | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev gcc-4.8
script:
  - make
