#ifndef SPRITE_STATE_H_
#define SPRITE_STATE_H_

enum class HorizontalFacing {
    FIRST_HORIZONTAL_FACING,
    LEFT = FIRST_HORIZONTAL_FACING,
    RIGHT,
    LAST_HORIZONTAL_FACING
};
enum class VerticalFacing {
    FIRST_VERTICAL_FACING,
    UP = FIRST_VERTICAL_FACING,
    DOWN,
    HORIZONTAL,
    LAST_VERTICAL_FACING
};

#endif /* SPRITE_STATE_H_ */

